### ISSUE TITLE
PostgreSQL example?

### ISSUE THREAD

**Issue by IvoLeist** [obiba/docker-opal#13]
Hello,

we are thinking about to use Opal for the web application I am developing right now.
However, for our use case we would need an Opal using PostgreSQL as backend and not mongo.

Could you aid us through the progress how to setting that up?

So far I only managed to modify the docker-compose in such a way that a PostgreSQL instance is started
(see below) But I am struggling to initialize Opal IDs database and Opal data database with PostgreSQL.

Best,
Ivo

```
version: '3'
services:
  opal:
    # build: .
    image: obiba/opal:snapshot
    ports:
      - "8843:8443"
      - "8880:8080"
    links:
      - rserver
      - mongo
      - mysqldata
      - postgresdata
    environment:
      - JAVA_OPTS=-Xms1G -Xmx8G -XX:+UseG1GC
      - OPAL_ADMINISTRATOR_PASSWORD=password
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MYSQLDATA_HOST=mysqldata
      - MYSQLDATA_USER=opal
      - MYSQLDATA_PASSWORD=password
      - POSTGRES_HOST=mysqldata
      - POSTGRES_USER=opal
      - POSTGRESDATA_PASSWORD=password
      - RSERVER_HOST=rserver
    volumes:
      - /tmp/opal:/srv
  mongo:
    image: mongo
  mysqldata:
    image: mysql:5
    environment:
      - MYSQL_DATABASE=opal
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=opal
      - MYSQL_PASSWORD=password
  postgresdata:
    image: postgres
    environment:
      - POSTGRES_DB=opal
      - POSTGRES_USER=opal
      - POSTGRES_PASSWORD=password
  rserver:
    image: obiba/opal-rserver:latest
    volumes:
      - /tmp/rserver:/srv

```

**Comment by ymarcon** [comment]
This is because the setup script [first_run.sh](https://github.com/obiba/docker-opal/blob/master/bin/first_run.sh) does not handle POSTGRES (and MARIADB) parameters... Your request is a good opportunity to finalize this work. Will do it by tomorrow.

**Comment by IvoLeist** [comment]
@ymarcon thank you for your swift reply :) 
Looking forward to test it!

**Comment by IvoLeist** [comment]
@ymarcon you are still working on it, right?

I just merged your last commit into my fork: https://github.com/ivoLeist/docker-opal
and now my opal somehow crashes :thinking: 

> No R server is running. Some functionalities will not work properly: data import/export using R, data and resource assignment to R server session, reporting etc.Administrate R server
> No resource description providers could be identified. You may need to install the resourcer R package.Administrate R packages
> No identifiers database is defined. No identifiers mapping can be performed when importing or exporting data.Add ID database
> No data database is defined. No data can be imported. Only views can be added.Add data database

**Comment by IvoLeist** [comment]
@ymarcon thank you for the quick addition of an updated docker compose file :)
The error above is now gone but now I am confused how to run it with only postgres as identifiers and main database?

If I comment out mongo and mariaDB and mysq it seems to be stuck when `docker-compose up`

> opal_1          | 2020-08-26 09:58:26,539 [cluster-ClusterId{value='5f46316685b4b9003400fa30', description='null'}-mongo:27017] INFO  org.mongodb.driver.cluster - Exception in monitor thread while connecting to server mongo:27017
> opal_1          | com.mongodb.MongoSocketException: mongo: Temporary failure in name resolution
> opal_1          | 	at com.mongodb.ServerAddress.getSocketAddresses(ServerAddress.java:211) ~[mongodb-driver-core-3.9.1.jar:na]
> opal_1          | 	at com.mongodb.internal.connection.SocketStream.initializeSocket(SocketStream.java:75) ~[mongodb-driver-core-3.9.1.jar:na]
> opal_1          | 	at com.mongodb.internal.connection.SocketStream.open(SocketStream.java:65) ~[mongodb-driver-core-3.9.1.jar:na]
> opal_1          | 	at com.mongodb.internal.connection.InternalStreamConnection.open(InternalStreamConnection.java:126) ~[mongodb-driver-core-3.9.1.jar:na]
> opal_1          | 	at com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:117) ~[mongodb-driver-core-3.9.1.jar:na]
> opal_1          | 	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_242]
> opal_1          | Caused by: java.net.UnknownHostException: mongo: Temporary failure in name resolution
> opal_1          | 	at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method) ~[na:1.8.0_242]
> opal_1          | 	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:929) ~[na:1.8.0_242]
> opal_1          | 	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1324) ~[na:1.8.0_242]
> opal_1          | 	at java.net.InetAddress.getAllByName0(InetAddress.java:1277) ~[na:1.8.0_242]
> opal_1          | 	at java.net.InetAddress.getAllByName(InetAddress.java:1193) ~[na:1.8.0_242]
> opal_1          | 	at java.net.InetAddress.getAllByName(InetAddress.java:1127) ~[na:1.8.0_242]
> opal_1          | 	at com.mongodb.ServerAddress.getSocketAddresses(ServerAddress.java:203) ~[mongodb-driver-core-3.9.1.jar:na]
> opal_1          | 	... 5 common frames omitted

**Comment by ymarcon** [comment]
This is an *initialization* script only. So if you remove containers from the network for which there is a database setup in Opal, it will not work.

For having the IDs database in postgres, you will need:
* an additional  postgres container for (let's call it postgresids)
* set up with `POTGRESIDS_*` env variables (in addition to the `POSTGRESDATA_*` ones) 

Something like:

```
version: '3'
services:
        opal:
                image: obiba/opal:snapshot
                #build: .
                ports:
                        - "8843:8443"
                        - "8880:8080"
                links:
                        - postgresids
                        - postgresdata
                        - rserver
                environment:
                        - OPAL_ADMINISTRATOR_PASSWORD=password
                        - POSTGRESIDS_DATABASE=opal
                        - POSTGRESIDS_HOST=postgresdata
                        - POSTGRESIDS_USER=opal
                        - POSTGRESIDS_PASSWORD=password
                        - POSTGRESDATA_DATABASE=opal
                        - POSTGRESDATA_HOST=postgresdata
                        - POSTGRESDATA_USER=opal
                        - POSTGRESDATA_PASSWORD=password
                        - RSERVER_HOST=rserver
                volumes:
                        - /tmp/test-opal:/srv
        postgresids:
                image: postgres
                environment:
                        - POSTGRES_DB=opal
                        - POSTGRES_USER=opal
                        - POSTGRES_PASSWORD=password
        postgresdata:
                image: postgres
                environment:
                        - POSTGRES_DB=opal
                        - POSTGRES_USER=opal
                        - POSTGRES_PASSWORD=password
        rserver:
                image: obiba/opal-rserver:latest
                volumes:
                        - /tmp/rserver:/srv
```

As a side note, having a database of IDs is not a requirement, it is only useful if you want to map some IDs when importing or exporting data.
