### ISSUE TITLE
user administrator not set

### ISSUE THREAD

**Issue by ciropom** [obiba/docker-opal#18]
Hello All, I expected that the opal docker container contains a default user and password (administrator/password)
but it looks like it's not.

I'm using the following docker-compose

```
services:
  opal:
    image: obiba/opal:4.4
    ports:
      - "8870:8080"
    depends_on:
      - mongo
      - rock
    environment:
#      - OPAL_ADMINISTRATOR_PASSWORD=visual-password
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - ROCK_HOSTS=rock:8085

  rock:
    image: datashield/rock-base:latest
    environment:
      - ROCK_ID=default-1
      - ROCK_CLUSTER=default

  mongo-express:
    image: mongo-express
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
      
  mongo:
    image: mongo:4.4.15
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: example

```

if I check users from commandline I get
```
> docker exec -it visualshield-opal-1 opal user --opal http://opal:8080 --user administrator --password password --fetch
[]
```

If I try to login from the web interface on port 8870, it says "authentication failed"

**Comment by ciropom** [comment]
If I try to update the password from command-line, inside the container

```
# opal user -o https://localhost:8443 -u administrator -p password --add --name administrator --upassword password -v
* Content:
{"name": "administrator", "authenticationType": "PASSWORD", "password": "password"}
*   Trying 127.0.0.1:8443...
* Connected to localhost (127.0.0.1) port 8443 (#0)
* found 387 certificates in /etc/ssl/certs
* ALPN, offering h2
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_256_GCM_SHA384
*        server certificate verification SKIPPED
*        server certificate status verification SKIPPED
*        common name: localhost (matched)
*        server certificate expiration date OK
*        server certificate activation date OK
*        certificate public key: RSA
*        certificate version: #3
*        subject: CN=localhost,OU=Opal,O=localhost,L=#0c00,ST=#0c00,C=#1300
*        start date: Wed, 13 Jul 2022 06:52:06 GMT
*        expire date: Fri, 05 Jul 2052 06:52:06 GMT
*        issuer: CN=localhost,OU=Opal,O=localhost,L=#0c00,ST=#0c00,C=#1300
* ALPN, server did not agree to a protocol
> POST /ws/system/subject-credentials HTTP/1.1
Host: localhost:8443
User-Agent: PycURL/7.43.0.6 libcurl/7.74.0 GnuTLS/3.7.1 zlib/1.2.11 brotli/1.0.9 libidn2/2.3.0 libpsl/0.21.0 (+libidn2/2.3.0) libssh2/1.9.0 nghttp2/1.43.0 librtmp/2.3
Authorization: Basic YWRtaW5pc3RyYXRvcjpwYXNzd29yZA==
Accept: application/json
Content-Type: application/json
Content-Length: 83

* upload completely sent off: 83 out of 83 bytes
* Mark bundle as not supporting multiuse
* The requested URL returned error: 400 Bad Request
* Closing connection 0
(22, 'The requested URL returned error: 400 Bad Request')
```

**Comment by ymarcon** [comment]
1. there is a ["opal" system user without password](https://github.com/obiba/docker-opal/blob/4.4.x/Dockerfile#L77), then it is not meant for using with docker exec
2. the opal server comes with a default user "administrator" that is declared in the shiro.ini file. 
    a. You MUST provide the `OPAL_ADMINISTRATOR_PASSWORD` env at first run of the docker. There is no default password. If not provided, your installation is broken.
    b. If you need to set or change the "administrator" password, follow the [File based User Directory](https://opaldoc.obiba.org/en/latest/admin/configuration.html#user-directories) procedure, i.e. use the **shiro-hasher** tool and not the opal command line.

**Comment by ciropom** [comment]
Hello, first of all, thank you for your answer.
Even if I enable the OPAL_ADMINISTRATOR_PASSWORD env variable I still can't login.

This is the docker-compose

```
services:
  opal:
    image: obiba/opal:4.4
#    build: opal
    ports:
      - "8870:8080"
    depends_on:
      - mongo
      - rock
    environment:
      - OPAL_ADMINISTRATOR_PASSWORD=password
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - ROCK_HOSTS=rock:8085
    volumes:
      - C:\Users\Tomasoni\git\VisualSHIELD\opal\opal-home:/srv/opal-home

  rock:
    #image: datashield/rock-base:latest
    build: rock-visualshield
    ports:
      - 8085:8085
    environment:
      - ROCK_ID=default-1
      - ROCK_CLUSTER=default

  mongo-express:
    image: mongo-express
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
      
  mongo:
    image: mongo:4.2
    ports:
      - 27017:27017
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: example
```

This is the opal log

```
visualshield-opal-1           | Preparing default conf in /srv ...
visualshield-opal-1           | Preparing default plugins in /srv ...
visualshield-opal-1           | Disabling default Agate setting as AGATE_HOST is not defined...
visualshield-opal-1           | Setting Rock R server connection...
visualshield-opal-1           | Setting password...
visualshield-opal-1           | SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
visualshield-opal-1           | SLF4J: Defaulting to no-operation (NOP) logger implementation
visualshield-opal-1           | SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
visualshield-opal-1           | Starting Opal before first run script...
visualshield-opal-1           | Waiting for Opal to be ready...
visualshield-opal-1           | JAVA_OPTS=-Xms1G -Xmx2G -XX:MaxPermSize=256M -XX:+UseG1GC
visualshield-opal-1           | OPAL_HOME=/srv
visualshield-opal-1           | OPAL_DIST=/usr/share/opal
visualshield-opal-1           | OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=256M; support was removed in 8.0
visualshield-opal-1           |  __    __    __      ____  _____        _
visualshield-opal-1           |  \ \   \ \   \ \    / __ \|  __ \ /\   | |
visualshield-opal-1           |   \ \   \ \   \ \  | |  | | |__) /  \  | |
visualshield-opal-1           |    > >   > >   > > | |  | |  ___/ /\ \ | |
visualshield-opal-1           |   / /   / /   / /  | |__| | |  / ____ \| |____
visualshield-opal-1           |  /_/   /_/   /_/    \____/|_| /_/    \_\______|
visualshield-opal-1           |
visualshield-opal-1           |
visualshield-opal-1           | Upgrading Opal...
visualshield-opal-1           | Upgrade successful.
visualshield-opal-1           | Starting Opal...
visualshield-opal-1           | Opal Server successfully started.
visualshield-opal-1           | Opal is attached to this console. Press ctrl-c to stop.
visualshield-opal-1           | First run setup...
visualshield-opal-1           | Initializing Opal IDs database with MongoDB...
visualshield-opal-1           | Enter content:
visualshield-opal-1           |
visualshield-opal-1           | Initializing Opal data database with MongoDB...
visualshield-opal-1           | Enter content:
visualshield-opal-1           |
visualshield-opal-1           | Initializing Datashield default profile...
visualshield-opal-1           |
visualshield-opal-1           |
visualshield-opal-1           | opal-analysis-validate-1.1.0
visualshield-opal-1           | opal-datasource-googlesheets4-1.1.0
visualshield-opal-1           | opal-datasource-limesurvey-1.3.0
visualshield-opal-1           | opal-datasource-readr-1.2.0
visualshield-opal-1           | opal-datasource-readxl-1.2.0
visualshield-opal-1           | opal-datasource-redcap-1.2.0
visualshield-opal-1           | opal-datasource-spss-1.2.0
visualshield-opal-1           | opal-search-es-1.1.0
visualshield-opal-1           | 2022-07-13 08:41:37,103 [qtp2021466012-44] INFO  org.apache.shiro.session.mgt.AbstractValidatingSessionManager - Enabling session validation scheduler...
visualshield-opal-1           | 2022-07-13 08:41:37,107 [qtp2021466012-44] INFO  org.apache.shiro.cache.ehcache.EhCacheManager - Using existing EHCache named [shiro-activeSessionCache]
visualshield-opal-1           | 2022-07-13 08:41:37,127 [qtp2021466012-44] INFO  org.obiba.opal.fs.OpalFileSystem - Setting up Opal filesystem rooted at 'file:///srv/fs'
visualshield-opal-1           | 2022-07-13 08:41:37,139 [qtp2021466012-44] INFO  org.apache.commons.vfs2.impl.StandardFileSystemManager - Using "/tmp/vfs_cache" as temporary files store.
visualshield-opal-1           | 2022-07-13 08:41:37,170 [pool-7-thread-1] INFO  org.obiba.opal.core.service.ProjectsServiceImpl - Resource providers ready, scanning for views to initialise...
visualshield-opal-1           | 2022-07-13 08:41:37,172 [Timer-2] INFO  org.obiba.opal.core.service.ProjectsServiceImpl - Resource providers ready, scanning for views to initialise...
visualshield-opal-1           | 2022-07-13 08:41:37,177 [qtp2021466012-44] INFO  org.obiba.opal.fs.OpalFileSystem - Opal File System does not exist. Trying to create it.
visualshield-opal-1           | 2022-07-13 08:41:37,183 [qtp2021466012-44] INFO  org.obiba.opal.core.service.SubjectProfileServiceImpl - Creating user home: /home/administrator
visualshield-opal-1           | 2022-07-13 08:41:37,195 [qtp2021466012-44] INFO  org.obiba.opal.core.service.security.realm.SpatialRealm - Clear cache perms for USER:administrator
visualshield-opal-1           | 2022-07-13 08:41:37,201 [qtp2021466012-44] INFO  org.obiba.opal.core.service.security.realm.SpatialRealm - Clear cache perms for USER:administrator
visualshield-opal-1           | 2022-07-13 08:41:50,005 [qtp2021466012-143] WARN  org.obiba.opal.web.security.CSRFInterceptor - CSRF detection: Host=localhost:8870, Referer=http://localhost:8870/ui/index.html
visualshield-opal-1           | 2022-07-13 08:41:50,005 [qtp2021466012-143] INFO  org.obiba.opal.web.security.CSRFInterceptor - >> You can add localhost:8870 to csrf.allowed setting
visualshield-opal-1           | 2022-07-13 08:41:50,006 [qtp2021466012-40] WARN  org.obiba.opal.web.security.CSRFInterceptor - CSRF detection: Host=localhost:8870, Referer=http://localhost:8870/ui/index.html
visualshield-opal-1           | 2022-07-13 08:41:50,006 [qtp2021466012-40] INFO  org.obiba.opal.web.security.CSRFInterceptor - >> You can add localhost:8870 to csrf.allowed setting
visualshield-opal-1           | 2022-07-13 08:41:50,025 [qtp2021466012-43] WARN  org.obiba.opal.web.security.CSRFInterceptor - CSRF detection: Host=localhost:8870, Referer=http://localhost:8870/ui/index.html
visualshield-opal-1           | 2022-07-13 08:41:50,025 [qtp2021466012-151] WARN  org.obiba.opal.web.security.CSRFInterceptor - CSRF detection: Host=localhost:8870, Referer=http://localhost:8870/ui/index.html
visualshield-opal-1           | 2022-07-13 08:41:50,025 [qtp2021466012-43] INFO  org.obiba.opal.web.security.CSRFInterceptor - >> You can add localhost:8870 to csrf.allowed setting
visualshield-opal-1           | 2022-07-13 08:41:50,025 [qtp2021466012-151] INFO  org.obiba.opal.web.security.CSRFInterceptor - >> You can add localhost:8870 to csrf.allowed setting
visualshield-opal-1           | 2022-07-13 08:41:50,044 [qtp2021466012-39] WARN  org.obiba.opal.web.security.CSRFInterceptor - CSRF detection: Host=localhost:8870, Referer=http://localhost:8870/ui/index.html
visualshield-opal-1           | 2022-07-13 08:41:50,044 [qtp2021466012-143] WARN  org.obiba.opal.web.security.CSRFInterceptor - CSRF detection: Host=localhost:8870, Referer=http://localhost:8870/ui/index.html
visualshield-opal-1           | 2022-07-13 08:41:50,045 [qtp2021466012-39] INFO  org.obiba.opal.web.security.CSRFInterceptor - >> You can add localhost:8870 to csrf.allowed setting
visualshield-opal-1           | 2022-07-13 08:41:50,045 [qtp2021466012-143] INFO  org.obiba.opal.web.security.CSRFInterceptor - >> You can add localhost:8870 to csrf.allowed setting
visualshield-opal-1           | 2022-07-13 08:41:50,064 [qtp2021466012-43] WARN  org.obiba.opal.web.security.CSRFInterceptor - CSRF detection: Host=localhost:8870, Referer=http://localhost:8870/ui/index.html
visualshield-opal-1           | 2022-07-13 08:41:50,064 [qtp2021466012-151] WARN  org.obiba.opal.web.security.CSRFInterceptor - CSRF detection: Host=localhost:8870, Referer=http://localhost:8870/ui/index.html
visualshield-opal-1           | 2022-07-13 08:41:50,064 [qtp2021466012-43] INFO  org.obiba.opal.web.security.CSRFInterceptor - >> You can add localhost:8870 to csrf.allowed setting
visualshield-opal-1           | 2022-07-13 08:41:50,064 [qtp2021466012-151] INFO  org.obiba.opal.web.security.CSRFInterceptor - >> You can add localhost:8870 to csrf.allowed setting
visualshield-opal-1           | 2022-07-13 08:41:54,297 [qtp2021466012-39] WARN  org.obiba.opal.web.security.CSRFInterceptor - CSRF detection: Host=localhost:8870, Referer=http://localhost:8870/ui/index.html
visualshield-opal-1           | 2022-07-13 08:41:54,298 [qtp2021466012-39] INFO  org.obiba.opal.web.security.CSRFInterceptor - >> You can add localhost:8870 to csrf.allowed setting
```
