### ISSUE TITLE
Reinitialization of mongodb at every docker-compose up

### ISSUE THREAD

**Issue by ciropom** [obiba/docker-opal#19]
Hello, I don't understand why with my docker-compose file

```
services:
  opal:
    image: obiba/opal:4.4
#    build: opal
    ports:
      - "8870:8080"
      - "8843:8443"
    depends_on:
      - mongo
      - rock
    environment:
      - OPAL_ADMINISTRATOR_PASSWORD=password
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - ROCK_HOSTS=rock:8085
    volumes:
      - /data/git/VisualSHIELD/opal/conf:/srv/conf
  rock:
    image: datashield/rock-base:latest
    ports:
      - 8085:8085
    environment:
      - ROCK_ID=default-1
      - ROCK_CLUSTER=default

  mongo-express:
    image: mongo-express
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/

  mongo:
    image: mongo:4.2
    command: --serviceExecutor adaptive --wiredTigerCacheSizeGB 2
    restart: always
    deploy:
      resources:
        limits:
          memory: 6gb
        reservations:
          memory: 4gb
    volumes:
      - /data/db:/data/db
```

Every time I type `docker-compose up` I see this reinitialization message of the mongodb:

```
| Opal Server successfully started.
visualshield-opal-1           | Opal is attached to this console. Press ctrl-c to stop.
visualshield-opal-1           | First run setup...
visualshield-opal-1           | Initializing Opal IDs database with MongoDB...
visualshield-opal-1           | Enter content:
visualshield-opal-1           |
visualshield-opal-1           | Initializing Opal data database with MongoDB...
visualshield-opal-1           | Enter content:
visualshield-opal-1           |
visualshield-opal-1           | Initializing Datashield default profile...
```

even if the volume pointing to the db is mounted and filled with the data of a previous execution.
Why the opal image don't understand that the mongodb was already initialized?
Thank you
